#!/usr/bin/env python
#  Copyright 2017 Keegan Joseph Brophy
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

"""Usage:
	teq initdb
	teq execute (FUNCTION) [ARGS]
	teq intake (<FILE>)...
	teq populate (<FILE>)...
	teq autovet
	teq -h --help

Options:
	execute (docustomexport)[Table] Any table form class.py
	execute (docustomimport)[Table]	Any table form class.py
	populate [file location] gen all data from offerings folder program will crash if the year exceeds 2030

"""

import db
import docopt

if __name__ == '__main__':
	arguments = docopt.docopt(__doc__)

	database = db.get()
	database.connect()

	if arguments['initdb']:
		db.init(database)

	try:
		function = (arguments['FUNCTION'])
		arg = str(arguments['ARGS'])
		filename = arguments['<FILE>']

		if arguments['intake']:
			from import_courses import import_courses
			import_courses(filename)
		else:
			import Core
			if function == 'docustomexport':
				Core.docustomexport(arg)
			if function == 'docustomimport':
				Core.docustomimport(arg)
			if function == 'deficits':
				Core.test()
			if arguments['populate']:
				Core.populate(filename)
			if arguments['autovet']:
				Core.percent()
	except docopt.DocoptExit as e:
		print e.message

	database.close()
